spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/postgres_test
    username: ${DB_USERNAME:postgres_test}
    password: ${DB_PASSWORD:postgres_test}
    driver-class-name: org.postgresql.Driver

  flyway:
    clean-disabled: false