spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_test
    username: postgres_test
    password: postgres_test
    driver-class-name: org.postgresql.Driver

  flyway:
    clean-disabled: false