name: Java CI with Maven

on:
  push:
    branches: [ "main", "master", "develop", "qa" ]
  pull_request:
    branches: [ "main", "master", "develop", "qa" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.6-alpine
        env:
          POSTGRES_DB: postgres_test
          POSTGRES_USER: postgres_test
          POSTGRES_PASSWORD: postgres_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Configure Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests with Maven
        run: chmod +x mvnw
        
      - name: Check Code Formatting
        run: ./mvnw spring-javaformat:validate

      - name: Run test with test profile
        env:
          DB_PORT: 5432
        run: ./mvnw clean test -Dspring.profiles.active=test
